// Dependency and file signals used by the fingerprint. Pure data: add entries, not logic.
// Keys are package names (npm, PyPI normalized to lowercase with dashes, Go module paths, gems, crates).
// Fields: stack(s), framework, needs, caps (capability evidence: which facet of a need, e.g. Excel rather than
// any office format), platforms (web, mobile, desktop), llm, data, test.

const m = (o) => o;

export const DEP_MAP = {
  // JavaScript / TypeScript frameworks
  next: m({ stacks: ["nextjs", "react"], framework: "next", needs: ["frontend-ui"], platforms: ["web"] }),
  react: m({ stacks: ["react"], framework: "react", needs: ["frontend-ui"] }),
  vue: m({ stacks: ["vue"], framework: "vue", needs: ["frontend-ui"], platforms: ["web"] }),
  nuxt: m({ stacks: ["nuxt", "vue"], framework: "nuxt", needs: ["frontend-ui"], platforms: ["web"] }),
  svelte: m({ stacks: ["svelte"], framework: "svelte", needs: ["frontend-ui"], platforms: ["web"] }),
  "@sveltejs/kit": m({ stacks: ["svelte"], framework: "sveltekit", needs: ["frontend-ui"], platforms: ["web"] }),
  astro: m({ stacks: ["astro"], framework: "astro", needs: ["frontend-ui", "seo"], platforms: ["web"] }),
  "@angular/core": m({ stacks: ["angular"], framework: "angular", needs: ["frontend-ui"], platforms: ["web"] }),
  "react-dom": m({ platforms: ["web"] }),
  express: m({ stacks: ["express"], framework: "express" }),
  fastify: m({ stacks: ["fastify"], framework: "fastify" }),
  "@nestjs/core": m({ stacks: ["nestjs"], framework: "nestjs" }),
  hono: m({ framework: "hono" }),
  koa: m({ framework: "koa" }),
  vite: m({ framework: "vite" }),
  tailwindcss: m({ framework: "tailwind", needs: ["frontend-ui"], stacks: ["tailwind"] }),
  "react-native": m({ stacks: ["react-native"], framework: "react-native", needs: ["mobile"], platforms: ["mobile"] }),
  "react-native-web": m({ platforms: ["web"] }),
  expo: m({ stacks: ["expo", "react-native"], framework: "expo", needs: ["mobile"], platforms: ["mobile"] }),
  electron: m({ stacks: ["electron"], framework: "electron", platforms: ["desktop", "web"] }),
  "@tauri-apps/api": m({ stacks: ["tauri"], framework: "tauri", platforms: ["desktop", "web"] }),
  typescript: m({ stacks: ["typescript"] }),
  // Payments and auth
  stripe: m({ needs: ["payments"], stacks: ["stripe"] }),
  "@stripe/stripe-js": m({ needs: ["payments"], stacks: ["stripe"] }),
  "@stripe/react-stripe-js": m({ needs: ["payments"], stacks: ["stripe"] }),
  "next-auth": m({ needs: ["auth"] }),
  "@auth/core": m({ needs: ["auth"] }),
  "@clerk/nextjs": m({ needs: ["auth"] }),
  "@clerk/clerk-react": m({ needs: ["auth"] }),
  passport: m({ needs: ["auth"] }),
  lucia: m({ needs: ["auth"] }),
  "better-auth": m({ needs: ["auth"] }),
  firebase: m({ needs: ["auth"], data: "firebase", stacks: ["firebase"] }),
  "firebase-admin": m({ data: "firebase", stacks: ["firebase"] }),
  // LLM SDKs
  openai: m({ llm: "openai", needs: ["llm-calls"] }),
  "@anthropic-ai/sdk": m({ llm: "anthropic", needs: ["llm-calls"] }),
  anthropic: m({ llm: "anthropic", needs: ["llm-calls"] }),
  ai: m({ llm: "vercel-ai", needs: ["llm-calls"] }),
  langchain: m({ llm: "langchain", needs: ["llm-calls"] }),
  "@langchain/core": m({ llm: "langchain", needs: ["llm-calls"] }),
  llamaindex: m({ llm: "llamaindex", needs: ["llm-calls"] }),
  "llama-index": m({ llm: "llamaindex", needs: ["llm-calls"] }),
  "@google/genai": m({ llm: "gemini", needs: ["llm-calls"] }),
  "@google/generative-ai": m({ llm: "gemini", needs: ["llm-calls"] }),
  "google-genai": m({ llm: "gemini", needs: ["llm-calls"] }),
  "google-generativeai": m({ llm: "gemini", needs: ["llm-calls"] }),
  ollama: m({ llm: "ollama", needs: ["llm-calls"] }),
  "groq-sdk": m({ llm: "groq", needs: ["llm-calls"] }),
  groq: m({ llm: "groq", needs: ["llm-calls"] }),
  "@mistralai/mistralai": m({ llm: "mistral", needs: ["llm-calls"] }),
  mistralai: m({ llm: "mistral", needs: ["llm-calls"] }),
  litellm: m({ llm: "litellm", needs: ["llm-calls"] }),
  transformers: m({ llm: "transformers", needs: ["llm-calls", "data-processing"] }),
  "github.com/sashabaranov/go-openai": m({ llm: "openai", needs: ["llm-calls"] }),
  "@modelcontextprotocol/sdk": m({ needs: ["mcp-server"] }),
  mcp: m({ needs: ["mcp-server"] }),
  // Data
  prisma: m({ data: "prisma", stacks: ["prisma"] }),
  "@prisma/client": m({ data: "prisma", stacks: ["prisma"] }),
  "drizzle-orm": m({ data: "drizzle" }),
  mongoose: m({ data: "mongodb", stacks: ["mongodb"] }),
  mongodb: m({ data: "mongodb", stacks: ["mongodb"] }),
  pymongo: m({ data: "mongodb", stacks: ["mongodb"] }),
  pg: m({ data: "postgres", stacks: ["postgres"] }),
  "psycopg": m({ data: "postgres", stacks: ["postgres"] }),
  "psycopg2-binary": m({ data: "postgres", stacks: ["postgres"] }),
  mysql2: m({ data: "mysql" }),
  redis: m({ data: "redis", stacks: ["redis"] }),
  ioredis: m({ data: "redis", stacks: ["redis"] }),
  "@supabase/supabase-js": m({ data: "supabase", needs: ["auth"], stacks: ["supabase"] }),
  "@supabase/ssr": m({ data: "supabase", needs: ["auth"], stacks: ["supabase"] }),
  sqlalchemy: m({ data: "sqlalchemy" }),
  sequelize: m({ data: "sequelize" }),
  typeorm: m({ data: "typeorm" }),
  "better-sqlite3": m({ data: "sqlite" }),
  pandas: m({ data: "pandas", needs: ["data-processing"] }),
  polars: m({ data: "polars", needs: ["data-processing"] }),
  numpy: m({ needs: ["data-processing"] }),
  jupyter: m({ needs: ["data-processing"] }),
  // Tests
  jest: m({ test: "jest" }),
  vitest: m({ test: "vitest" }),
  mocha: m({ test: "mocha" }),
  ava: m({ test: "ava" }),
  "@playwright/test": m({ test: "playwright", needs: ["e2e-testing"] }),
  cypress: m({ test: "cypress", needs: ["e2e-testing"] }),
  pytest: m({ test: "pytest" }),
  // Files, scraping, SEO, office
  pdfkit: m({ needs: ["pdf"], caps: ["pdf-processing"] }),
  "pdf-lib": m({ needs: ["pdf"], caps: ["pdf-processing"] }),
  jspdf: m({ needs: ["pdf"], caps: ["pdf-processing"] }),
  "@react-pdf/renderer": m({ needs: ["pdf"], caps: ["pdf-processing"] }),
  "pdfjs-dist": m({ needs: ["pdf"], caps: ["pdf-processing"] }),
  pypdf: m({ needs: ["pdf"], caps: ["pdf-processing"] }),
  pypdf2: m({ needs: ["pdf"], caps: ["pdf-processing"] }),
  reportlab: m({ needs: ["pdf"], caps: ["pdf-processing"] }),
  pdfplumber: m({ needs: ["pdf"], caps: ["pdf-processing"] }),
  pymupdf: m({ needs: ["pdf"], caps: ["pdf-processing"] }),
  exceljs: m({ needs: ["office-docs", "data-processing"], caps: ["spreadsheets"] }),
  xlsx: m({ needs: ["office-docs", "data-processing"], caps: ["spreadsheets"] }),
  openpyxl: m({ needs: ["office-docs", "data-processing"], caps: ["spreadsheets"] }),
  docx: m({ needs: ["office-docs"], caps: ["docx-documents"] }),
  "python-docx": m({ needs: ["office-docs"], caps: ["docx-documents"] }),
  pptxgenjs: m({ needs: ["office-docs"], caps: ["presentations"] }),
  "python-pptx": m({ needs: ["office-docs"], caps: ["presentations"] }),
  cheerio: m({ needs: ["scraping"] }),
  puppeteer: m({ needs: ["scraping"] }),
  playwright: m({ needs: ["scraping", "e2e-testing"] }),
  crawlee: m({ needs: ["scraping"] }),
  "rss-parser": m({ needs: ["scraping"] }),
  scrapy: m({ needs: ["scraping"] }),
  beautifulsoup4: m({ needs: ["scraping"] }),
  selenium: m({ needs: ["scraping"] }),
  feedparser: m({ needs: ["scraping"] }),
  "@astrojs/sitemap": m({ needs: ["seo"] }),
  "next-sitemap": m({ needs: ["seo"] }),
  "next-seo": m({ needs: ["seo"] }),
  // Smart contracts
  hardhat: m({ stacks: ["solidity"], needs: ["smart-contracts"] }),
  "@openzeppelin/contracts": m({ stacks: ["solidity"], needs: ["smart-contracts"] }),
  ethers: m({ needs: ["smart-contracts"] }),
  viem: m({ needs: ["smart-contracts"] }),
  web3: m({ needs: ["smart-contracts"] }),
  "@solana/web3.js": m({ needs: ["smart-contracts"] }),
  // Python frameworks
  fastapi: m({ stacks: ["fastapi"], framework: "fastapi" }),
  django: m({ stacks: ["django"], framework: "django" }),
  flask: m({ stacks: ["flask"], framework: "flask" }),
  streamlit: m({ framework: "streamlit", needs: ["data-processing"] }),
  // Go, Rust, Ruby, PHP, Dart
  "github.com/spf13/cobra": m({ framework: "cobra" }),
  "github.com/urfave/cli/v2": m({ framework: "urfave-cli" }),
  "github.com/gin-gonic/gin": m({ framework: "gin" }),
  "github.com/gofiber/fiber/v2": m({ framework: "fiber" }),
  "github.com/labstack/echo/v4": m({ framework: "echo" }),
  "github.com/stripe/stripe-go/v81": m({ needs: ["payments"] }),
  clap: m({ framework: "clap" }),
  // Command-line frameworks (they make a project a CLI tool).
  click: m({ framework: "click" }),
  typer: m({ framework: "typer" }),
  fire: m({ framework: "fire" }),
  commander: m({ framework: "commander" }),
  yargs: m({ framework: "yargs" }),
  "@oclif/core": m({ framework: "oclif" }),
  "github.com/urfave/cli/v3": m({ framework: "urfave-cli" }),
  axum: m({ framework: "axum" }),
  "actix-web": m({ framework: "actix" }),
  tokio: m({ framework: "tokio" }),
  rails: m({ stacks: ["rails"], framework: "rails" }),
  "laravel/framework": m({ stacks: ["laravel"], framework: "laravel" }),
  flutter: m({ stacks: ["flutter"], framework: "flutter", needs: ["mobile"], platforms: ["mobile"] }),
  // Products a project uses: a skill written for one of them is offered only where it is found.
  "aws-sdk": m({ stacks: ["aws"] }),
  "aws-cdk-lib": m({ stacks: ["aws"], needs: ["infra"] }),
  boto3: m({ stacks: ["aws"] }),
  wrangler: m({ stacks: ["cloudflare"], needs: ["deploy"] }),
  "@cloudflare/workers-types": m({ stacks: ["cloudflare"] }),
  remotion: m({ stacks: ["remotion", "react"], needs: ["media"] }),
  // Translations, media, games and science.
  i18next: m({ needs: ["i18n"] }),
  "react-i18next": m({ needs: ["i18n"] }),
  "next-intl": m({ needs: ["i18n"] }),
  "react-intl": m({ needs: ["i18n"] }),
  "vue-i18n": m({ needs: ["i18n"] }),
  "@angular/localize": m({ needs: ["i18n"] }),
  "fluent-ffmpeg": m({ needs: ["media"] }),
  "@ffmpeg/ffmpeg": m({ needs: ["media"] }),
  moviepy: m({ needs: ["media"] }),
  phaser: m({ needs: ["game-dev"] }),
  "pixi.js": m({ needs: ["game-dev"] }),
  babylonjs: m({ needs: ["game-dev"] }),
  "@babylonjs/core": m({ needs: ["game-dev"] }),
  pygame: m({ needs: ["game-dev"] }),
  biopython: m({ needs: ["scientific"] }),
  rdkit: m({ needs: ["scientific"] }),
  scanpy: m({ needs: ["scientific"] }),
  anndata: m({ needs: ["scientific"] }),
  astropy: m({ needs: ["scientific"] }),
  pysam: m({ needs: ["scientific"] }),
  mdanalysis: m({ needs: ["scientific"] }),
};

// Package-name prefixes for families of packages (cloud SDKs ship one package per service).
export const DEP_PREFIXES = [
  ["@aws-sdk/", m({ stacks: ["aws"] })],
  ["@azure/", m({ stacks: ["azure"] })],
  ["azure-", m({ stacks: ["azure"] })],
  ["@google-cloud/", m({ stacks: ["gcp"] })],
  ["google-cloud-", m({ stacks: ["gcp"] })],
  ["@supabase/", m({ stacks: ["supabase"] })],
  ["@firebase/", m({ stacks: ["firebase"] })],
  ["@remotion/", m({ stacks: ["remotion"], needs: ["media"] })],
];

// [regex on relative path, {infra?, stacks?, needs?, test?, agent?}]
export const FILE_MAP = [
  [/(^|\/)Dockerfile$|(^|\/)(docker-)?compose\.ya?ml$/, { infra: "docker", needs: ["deploy", "infra"], stacks: ["docker"] }],
  [/^\.github\/workflows\/[^/]+\.ya?ml$/, { infra: "github-actions", needs: ["ci"] }],
  [/^\.gitlab-ci\.yml$/, { infra: "gitlab-ci", needs: ["ci"] }],
  [/\.tf$/, { infra: "terraform", needs: ["deploy", "infra"], stacks: ["terraform"] }],
  [/^vercel\.json$/, { infra: "vercel", needs: ["deploy"], stacks: ["vercel"] }],
  [/^netlify\.toml$/, { infra: "netlify", needs: ["deploy"] }],
  [/^fly\.toml$/, { infra: "fly", needs: ["deploy"] }],
  [/^wrangler\.toml$/, { infra: "cloudflare", needs: ["deploy"], stacks: ["cloudflare"] }],
  [/(^|\/)firebase\.json$/, { stacks: ["firebase"] }],
  [/(^|\/)schema\.prisma$/, { stacks: ["prisma"], data: "prisma", needs: ["database"] }],
  [/^supabase\/config\.toml$/, { stacks: ["supabase"], data: "supabase" }],
  [/^cdk\.json$/, { stacks: ["aws"], needs: ["infra"] }],
  [/(^|\/)Chart\.yaml$|(^|\/)kustomization\.ya?ml$/, { stacks: ["kubernetes"], needs: ["infra"] }],
  [/^(turbo\.json|nx\.json|pnpm-workspace\.yaml|lerna\.json)$/, { needs: ["monorepo"] }],
  [/(^|\/)AndroidManifest\.xml$/, { needs: ["mobile"], platforms: ["mobile"] }],
  [/(^|\/)Podfile$|\.xcodeproj\/project\.pbxproj$/, { needs: ["mobile"], platforms: ["mobile"] }],
  [/(^|\/)project\.godot$/, { stacks: ["godot"], needs: ["game-dev"] }],
  [/^ProjectSettings\/ProjectVersion\.txt$/, { stacks: ["unity"], needs: ["game-dev"] }],
  [/\.uproject$/, { needs: ["game-dev"] }],
  [/(^|\/)(locales?|i18n|translations|lang)\/[^/]+\.(json|ya?ml|po)$/, { needs: ["i18n"] }],
  [/^serverless\.ya?ml$/, { infra: "serverless", needs: ["deploy"] }],
  [/(^|\/)hardhat\.config\.(js|ts|cjs|mjs)$|(^|\/)foundry\.toml$/, { stacks: ["solidity"], needs: ["smart-contracts"] }],
  [/(^|\/)playwright\.config\.(js|ts|mjs)$/, { test: "playwright", needs: ["e2e-testing"] }],
  [/_test\.go$/, { test: "go-test" }],
  [/(^|\/)(test_[^/]+\.py|[^/]+_test\.py)$/, { test: "pytest" }],
  [/\.(test|spec)\.(js|jsx|ts|tsx|mjs|cjs)$/, { test: "js-tests" }],
  [/^CLAUDE\.md$|^\.claude\//, { agent: "claude-code" }],
  [/^\.cursor\/|^\.cursorrules$/, { agent: "cursor" }],
  [/^AGENTS\.md$|^\.codex\//, { agent: "codex" }],
  [/^\.gemini\/|^GEMINI\.md$/, { agent: "gemini-cli" }],
];

export const LANG_BY_EXT = {
  ".ts": "typescript", ".tsx": "typescript", ".mts": "typescript", ".cts": "typescript",
  ".js": "javascript", ".jsx": "javascript", ".mjs": "javascript", ".cjs": "javascript",
  ".py": "python", ".go": "go", ".rs": "rust", ".java": "java", ".kt": "kotlin", ".swift": "swift",
  ".dart": "dart", ".rb": "ruby", ".php": "php", ".cs": "csharp", ".c": "cpp", ".h": "cpp", ".cpp": "cpp",
  ".cc": "cpp", ".hpp": "cpp", ".sol": "solidity", ".vue": "vue", ".svelte": "svelte", ".astro": "astro",
};

// Languages that imply a stack of the same name.
export const LANG_STACK = {
  typescript: "typescript", python: "python", go: "go", rust: "rust", java: "java", kotlin: "kotlin",
  swift: "swift", dart: "dart", ruby: "ruby", php: "php", csharp: "csharp", cpp: "cpp", solidity: "solidity",
};

export const FRONTEND_STACKS = ["react", "nextjs", "vue", "nuxt", "svelte", "astro", "angular", "flutter", "react-native"];
